// Math.random(): This function generates a random floating-point number between 0 (inclusive) and 1 (exclusive). The result is a number like 0.3487 or 0.9845.

// reviews.length: This property returns the number of elements in the reviews array. For example, if reviews has 10 elements, reviews.length will be 10.

// Math.random() * reviews.length: This multiplies the random number generated by Math.random() by the length of the reviews array. The result is a random floating-point number between 0 (inclusive) and reviews.length (exclusive). For instance, if reviews.length is 10, the result could be any floating-point number between 0 and 9.9999.

// Math.floor(): This function takes a floating-point number and rounds it down to the nearest integer. So, if the result from the previous step was 7.845, Math.floor(7.845) would round it down to 7.

import React from "react";
import Card from "./Card";
import { useState } from "react";
import { FiChevronLeft, FiChevronRight } from "react-icons/fi";

const Testimonials = (props) => {
  let reviews = props.reviews;
  const [index, setIndex] = useState(0);

  function leftShiftHandler() {
    if (index - 1 < 0) {
      setIndex(reviews.length - 1);
    } else {
      setIndex(index - 1);
    }
  }
  function rightShiftHandler() {
    if (index + 1 >= reviews.length) {
      setIndex(0);
    } else {
      setIndex(index + 1);
    }
  }

  //   idr se hum index ki value nikal laige uske baad card component me index me value bhejegai jis se uss particular index ka data card components me jayega, or index ki value ko increase and decrease ke liye function hai.

  function surpriseHandler() {
    let randomIndex = Math.floor(Math.random() * reviews.length);
    setIndex(randomIndex);
  }

  return (
    <div
      className="w-[85vw] md:w-[700px] bg-white flex flex-col justify-center items-center
    mt-10 p-10 transition-all duration-700 hover:shadow-xl rounded-md"
    >
      <Card review={reviews[index]}></Card>

      <div className="flex text-3xl mt-10 gap-3 text-violet-400 font-bold mx-auto">
        <button
          onClick={leftShiftHandler}
          className="cursor-pointer hover:text-violet-500 "
        >
          <FiChevronLeft />
        </button>
        <button
          onClick={rightShiftHandler}
          className="cursor-pointer hover:text-violet-500 "
        >
          <FiChevronRight />
        </button>
      </div>

      <div className="mt-6">
        <button
          onClick={surpriseHandler}
          className="bg-violet-400 hover:bg-violet-500 transition-all duration-200
        cursor-pointer px-10 py-2 rounded-md font-bold text-white text-lg"
        >
          Surprise Me
        </button>
      </div>
    </div>
  );
};

export default Testimonials;
